---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/4874/workspace/6webapp-CICD/target/6webapp.war"
        dest: "/opt/tomcat/webapps/"
        remote_src: no

